/* AUTO-GENERATED by backend/analysis/step0_7_build_swipe_deck.py — do not edit by hand.
   Real Jongno street photos (Wikimedia Commons + Mapillary), each snapped to a
   scored street. window.SWIPE_PAIRS drives the onboarding 'this or that' (one
   forced choice per axis); the app builds the base profile from those choices.
   window.SWIPE_CARDS is the full scored deck (kept for reference/fallback). */
window.SWIPE_AXES = [["touristy_local", "touristy", "local"], ["historic_contemporary", "historic", "contemporary"], ["raw_polished", "raw", "polished"], ["quiet_lively", "quiet", "lively"], ["local_chain", "independent", "chain"], ["park", "", "by a park"]];
window.SWIPE_PAIRS = [
  {
    "axis": "touristy_local",
    "neg": "touristy",
    "pos": "local",
    "left": {
      "id": "c150057362",
      "src": "assets/photos/swipe/c150057362.jpg",
      "place": "북촌로11길",
      "credit": "© Basile Morin · CC BY-SA 4.0",
      "scores": {
        "touristy_local": -0.333,
        "historic_contemporary": -0.2,
        "raw_polished": null,
        "quiet_lively": -0.783,
        "local_chain": 0.201,
        "park": -0.625
      }
    },
    "right": {
      "id": "m1778692433102699",
      "src": "assets/photos/swipe/m1778692433102699.jpg",
      "place": "계동길",
      "credit": "CC BY-SA 4.0 (Mapillary)",
      "scores": {
        "touristy_local": 0.5,
        "historic_contemporary": -0.333,
        "raw_polished": null,
        "quiet_lively": -0.247,
        "local_chain": 0.043,
        "park": -0.975
      }
    }
  },
  {
    "axis": "historic_contemporary",
    "neg": "historic",
    "pos": "contemporary",
    "left": {
      "id": "m229147956344960",
      "src": "assets/photos/swipe/m229147956344960.jpg",
      "place": "돈화문로10길",
      "credit": "CC BY-SA 4.0 (Mapillary)",
      "scores": {
        "touristy_local": 1.0,
        "historic_contemporary": -1.0,
        "raw_polished": null,
        "quiet_lively": 0.878,
        "local_chain": -0.056,
        "park": -0.824
      }
    },
    "right": {
      "id": "m1722868688600244",
      "src": "assets/photos/swipe/m1722868688600244.jpg",
      "place": "청계천로",
      "credit": "CC BY-SA 4.0 (Mapillary)",
      "scores": {
        "touristy_local": -1.0,
        "historic_contemporary": null,
        "raw_polished": 1.0,
        "quiet_lively": 0.346,
        "local_chain": 0.727,
        "park": 0.751
      }
    }
  },
  {
    "axis": "raw_polished",
    "neg": "raw",
    "pos": "polished",
    "left": {
      "id": "c41729716",
      "src": "assets/photos/swipe/c41729716.jpg",
      "place": "돈화문로11가길",
      "credit": "© yamarhythm · CC BY 3.0",
      "scores": {
        "touristy_local": 0.0,
        "historic_contemporary": 0.0,
        "raw_polished": -1.0,
        "quiet_lively": -0.449,
        "local_chain": 0.339,
        "park": -0.841
      }
    },
    "right": {
      "id": "m1048242196417295",
      "src": "assets/photos/swipe/m1048242196417295.jpg",
      "place": "삼청로",
      "credit": "CC BY-SA 4.0 (Mapillary)",
      "scores": {
        "touristy_local": 0.0,
        "historic_contemporary": 0.143,
        "raw_polished": 1.0,
        "quiet_lively": -0.091,
        "local_chain": 0.036,
        "park": -0.305
      }
    }
  },
  {
    "axis": "quiet_lively",
    "neg": "quiet",
    "pos": "lively",
    "left": {
      "id": "m1026409559902948",
      "src": "assets/photos/swipe/m1026409559902948.jpg",
      "place": "창신길",
      "credit": "CC BY-SA 4.0 (Mapillary)",
      "scores": {
        "touristy_local": 1.0,
        "historic_contemporary": -1.0,
        "raw_polished": -1.0,
        "quiet_lively": -0.867,
        "local_chain": 0.898,
        "park": -0.849
      }
    },
    "right": {
      "id": "c115671801",
      "src": "assets/photos/swipe/c115671801.jpg",
      "place": "인사동길",
      "credit": "© Mario Sánchez Prada · CC BY-SA 2.0",
      "scores": {
        "touristy_local": 0.333,
        "historic_contemporary": -0.5,
        "raw_polished": 1.0,
        "quiet_lively": 0.551,
        "local_chain": -0.227,
        "park": -0.985
      }
    }
  },
  {
    "axis": "local_chain",
    "neg": "independent",
    "pos": "chain",
    "left": {
      "id": "c54774571",
      "src": "assets/photos/swipe/c54774571.jpg",
      "place": "인사동14길",
      "credit": "© ccfarmer · CC BY 3.0",
      "scores": {
        "touristy_local": 0.333,
        "historic_contemporary": -1.0,
        "raw_polished": 1.0,
        "quiet_lively": 0.551,
        "local_chain": -0.697,
        "park": -1.0
      }
    },
    "right": {
      "id": "m1175838890376715",
      "src": "assets/photos/swipe/m1175838890376715.jpg",
      "place": "다동길",
      "credit": "CC BY-SA 4.0 (Mapillary)",
      "scores": {
        "touristy_local": 0.0,
        "historic_contemporary": -1.0,
        "raw_polished": 0.333,
        "quiet_lively": null,
        "local_chain": 0.477,
        "park": -0.511
      }
    }
  },
  {
    "axis": "park",
    "neg": "no park",
    "pos": "by a park",
    "left": {
      "id": "c54774571",
      "src": "assets/photos/swipe/c54774571.jpg",
      "place": "인사동14길",
      "credit": "© ccfarmer · CC BY 3.0",
      "scores": {
        "touristy_local": 0.333,
        "historic_contemporary": -1.0,
        "raw_polished": 1.0,
        "quiet_lively": 0.551,
        "local_chain": -0.697,
        "park": -1.0
      }
    },
    "right": {
      "id": "m1722868688600244",
      "src": "assets/photos/swipe/m1722868688600244.jpg",
      "place": "청계천로",
      "credit": "CC BY-SA 4.0 (Mapillary)",
      "scores": {
        "touristy_local": -1.0,
        "historic_contemporary": null,
        "raw_polished": 1.0,
        "quiet_lively": 0.346,
        "local_chain": 0.727,
        "park": 0.751
      }
    }
  }
];
window.SWIPE_CARDS = [
  {
    "id": "m1026409559902948",
    "src": "assets/photos/swipe/m1026409559902948.jpg",
    "place": "창신길",
    "scene": "Raw · local",
    "tags": [
      "raw",
      "local",
      "historic",
      "chain"
    ],
    "scores": {
      "touristy_local": 1.0,
      "historic_contemporary": -1.0,
      "raw_polished": -1.0,
      "quiet_lively": -0.867,
      "local_chain": 0.898,
      "park": -0.849
    },
    "credit": "CC BY-SA 4.0 (Mapillary)",
    "url": "https://www.mapillary.com/app/?pKey=1026409559902948&focus=photo"
  },
  {
    "id": "m1048242196417295",
    "src": "assets/photos/swipe/m1048242196417295.jpg",
    "place": "삼청로",
    "scene": "Polished",
    "tags": [
      "polished"
    ],
    "scores": {
      "touristy_local": 0.0,
      "historic_contemporary": 0.143,
      "raw_polished": 1.0,
      "quiet_lively": -0.091,
      "local_chain": 0.036,
      "park": -0.305
    },
    "credit": "CC BY-SA 4.0 (Mapillary)",
    "url": "https://www.mapillary.com/app/?pKey=1048242196417295&focus=photo"
  },
  {
    "id": "m1048790993702047",
    "src": "assets/photos/swipe/m1048790993702047.jpg",
    "place": "율곡로3길",
    "scene": "Polished",
    "tags": [
      "polished"
    ],
    "scores": {
      "touristy_local": 0.0,
      "historic_contemporary": 0.2,
      "raw_polished": 1.0,
      "quiet_lively": -0.141,
      "local_chain": 0.286,
      "park": -0.526
    },
    "credit": "CC BY-SA 4.0 (Mapillary)",
    "url": "https://www.mapillary.com/app/?pKey=1048790993702047&focus=photo"
  },
  {
    "id": "m1049781256800575",
    "src": "assets/photos/swipe/m1049781256800575.jpg",
    "place": "북촌로5길",
    "scene": "Local",
    "tags": [
      "local"
    ],
    "scores": {
      "touristy_local": 0.333,
      "historic_contemporary": 0.0,
      "raw_polished": null,
      "quiet_lively": -0.141,
      "local_chain": 0.207,
      "park": -0.543
    },
    "credit": "CC BY-SA 4.0 (Mapillary)",
    "url": "https://www.mapillary.com/app/?pKey=1049781256800575&focus=photo"
  },
  {
    "id": "c115671801",
    "src": "assets/photos/swipe/c115671801.jpg",
    "place": "인사동길",
    "scene": "Polished · lively",
    "tags": [
      "polished",
      "lively",
      "historic",
      "local"
    ],
    "scores": {
      "touristy_local": 0.333,
      "historic_contemporary": -0.5,
      "raw_polished": 1.0,
      "quiet_lively": 0.551,
      "local_chain": -0.227,
      "park": -0.985
    },
    "credit": "© Mario Sánchez Prada · CC BY-SA 2.0",
    "url": "https://commons.wikimedia.org/wiki/File:2012-05-11_Insadong_01.jpg"
  },
  {
    "id": "m1175838890376715",
    "src": "assets/photos/swipe/m1175838890376715.jpg",
    "place": "다동길",
    "scene": "Historic · chain",
    "tags": [
      "historic",
      "chain",
      "polished"
    ],
    "scores": {
      "touristy_local": 0.0,
      "historic_contemporary": -1.0,
      "raw_polished": 0.333,
      "quiet_lively": null,
      "local_chain": 0.477,
      "park": -0.511
    },
    "credit": "CC BY-SA 4.0 (Mapillary)",
    "url": "https://www.mapillary.com/app/?pKey=1175838890376715&focus=photo"
  },
  {
    "id": "m1247534357595968",
    "src": "assets/photos/swipe/m1247534357595968.jpg",
    "place": "삼일대로32길",
    "scene": "Polished · lively",
    "tags": [
      "polished",
      "lively",
      "local",
      "historic"
    ],
    "scores": {
      "touristy_local": 0.5,
      "historic_contemporary": -0.333,
      "raw_polished": 1.0,
      "quiet_lively": 0.551,
      "local_chain": 0.273,
      "park": -0.906
    },
    "credit": "CC BY-SA 4.0 (Mapillary)",
    "url": "https://www.mapillary.com/app/?pKey=1247534357595968&focus=photo"
  },
  {
    "id": "m1305602044901844",
    "src": "assets/photos/swipe/m1305602044901844.jpg",
    "place": "을지로",
    "scene": "Touristy · polished",
    "tags": [
      "touristy",
      "polished",
      "historic",
      "chain"
    ],
    "scores": {
      "touristy_local": -1.0,
      "historic_contemporary": -1.0,
      "raw_polished": 1.0,
      "quiet_lively": null,
      "local_chain": 0.332,
      "park": -0.396
    },
    "credit": "CC BY-SA 4.0 (Mapillary)",
    "url": "https://www.mapillary.com/app/?pKey=1305602044901844&focus=photo"
  },
  {
    "id": "c143478981",
    "src": "assets/photos/swipe/c143478981.jpg",
    "place": "북촌로11길",
    "scene": "Quiet · touristy",
    "tags": [
      "quiet",
      "touristy"
    ],
    "scores": {
      "touristy_local": -0.333,
      "historic_contemporary": -0.2,
      "raw_polished": null,
      "quiet_lively": -0.783,
      "local_chain": 0.201,
      "park": -0.625
    },
    "credit": "© Bgag · CC0",
    "url": "https://commons.wikimedia.org/wiki/File:Bukchon_Hanok_Village_01.jpg"
  },
  {
    "id": "c150057362",
    "src": "assets/photos/swipe/c150057362.jpg",
    "place": "북촌로11길",
    "scene": "Quiet · touristy",
    "tags": [
      "quiet",
      "touristy"
    ],
    "scores": {
      "touristy_local": -0.333,
      "historic_contemporary": -0.2,
      "raw_polished": null,
      "quiet_lively": -0.783,
      "local_chain": 0.201,
      "park": -0.625
    },
    "credit": "© Basile Morin · CC BY-SA 4.0",
    "url": "https://commons.wikimedia.org/wiki/File:Bukchon-ro_11-gil_street_with_hanok_houses_at_sunrise_in_Bukchon_Hanok_Village_Seoul.jpg"
  },
  {
    "id": "c163118944",
    "src": "assets/photos/swipe/c163118944.jpg",
    "place": "북촌로11길",
    "scene": "Quiet · touristy",
    "tags": [
      "quiet",
      "touristy"
    ],
    "scores": {
      "touristy_local": -0.333,
      "historic_contemporary": -0.2,
      "raw_polished": null,
      "quiet_lively": -0.783,
      "local_chain": 0.201,
      "park": -0.625
    },
    "credit": "© Epicgenius · CC BY-SA 4.0",
    "url": "https://commons.wikimedia.org/wiki/File:Bukchon_Hanok_Village_Mar_2025_01.jpg"
  },
  {
    "id": "m1722868688600244",
    "src": "assets/photos/swipe/m1722868688600244.jpg",
    "place": "청계천로",
    "scene": "Touristy · polished",
    "tags": [
      "touristy",
      "polished",
      "by a park",
      "chain"
    ],
    "scores": {
      "touristy_local": -1.0,
      "historic_contemporary": null,
      "raw_polished": 1.0,
      "quiet_lively": 0.346,
      "local_chain": 0.727,
      "park": 0.751
    },
    "credit": "CC BY-SA 4.0 (Mapillary)",
    "url": "https://www.mapillary.com/app/?pKey=1722868688600244&focus=photo"
  },
  {
    "id": "m1778692433102699",
    "src": "assets/photos/swipe/m1778692433102699.jpg",
    "place": "계동길",
    "scene": "Local · historic",
    "tags": [
      "local",
      "historic"
    ],
    "scores": {
      "touristy_local": 0.5,
      "historic_contemporary": -0.333,
      "raw_polished": null,
      "quiet_lively": -0.247,
      "local_chain": 0.043,
      "park": -0.975
    },
    "credit": "CC BY-SA 4.0 (Mapillary)",
    "url": "https://www.mapillary.com/app/?pKey=1778692433102699&focus=photo"
  },
  {
    "id": "c18063047",
    "src": "assets/photos/swipe/c18063047.jpg",
    "place": "북촌로12길",
    "scene": "Raw · historic",
    "tags": [
      "raw",
      "historic",
      "touristy"
    ],
    "scores": {
      "touristy_local": -0.6,
      "historic_contemporary": -1.0,
      "raw_polished": -1.0,
      "quiet_lively": -0.213,
      "local_chain": 0.089,
      "park": -0.856
    },
    "credit": "© Sakaori (talk) · CC BY-SA 3.0",
    "url": "https://commons.wikimedia.org/wiki/File:Area_east_of_Bukchon_Hanok_Village_A.JPG"
  },
  {
    "id": "c18063558",
    "src": "assets/photos/swipe/c18063558.jpg",
    "place": "북촌로",
    "scene": "Quiet · historic",
    "tags": [
      "quiet",
      "historic"
    ],
    "scores": {
      "touristy_local": -0.2,
      "historic_contemporary": -0.333,
      "raw_polished": null,
      "quiet_lively": -0.354,
      "local_chain": 0.227,
      "park": -0.782
    },
    "credit": "© Sakaori (talk) · CC BY-SA 3.0",
    "url": "https://commons.wikimedia.org/wiki/File:Area_east_of_Bukchon_Hanok_Village_B.JPG"
  },
  {
    "id": "c18063659",
    "src": "assets/photos/swipe/c18063659.jpg",
    "place": "북촌로11길",
    "scene": "Quiet · touristy",
    "tags": [
      "quiet",
      "touristy"
    ],
    "scores": {
      "touristy_local": -0.333,
      "historic_contemporary": -0.2,
      "raw_polished": null,
      "quiet_lively": -0.783,
      "local_chain": 0.201,
      "park": -0.625
    },
    "credit": "© Sakaori (talk) · CC BY-SA 3.0",
    "url": "https://commons.wikimedia.org/wiki/File:Area_west_of_Bukchon_Hanok_Village_A.JPG"
  },
  {
    "id": "c18063729",
    "src": "assets/photos/swipe/c18063729.jpg",
    "place": "북촌로11길",
    "scene": "Quiet · touristy",
    "tags": [
      "quiet",
      "touristy"
    ],
    "scores": {
      "touristy_local": -0.333,
      "historic_contemporary": -0.2,
      "raw_polished": null,
      "quiet_lively": -0.783,
      "local_chain": 0.201,
      "park": -0.625
    },
    "credit": "© Sakaori (talk) · CC BY-SA 3.0",
    "url": "https://commons.wikimedia.org/wiki/File:Area_west_of_Bukchon_Hanok_Village_B.JPG"
  },
  {
    "id": "c195957933",
    "src": "assets/photos/swipe/c195957933.jpg",
    "place": "북촌로",
    "scene": "Quiet · historic",
    "tags": [
      "quiet",
      "historic"
    ],
    "scores": {
      "touristy_local": -0.2,
      "historic_contemporary": -0.333,
      "raw_polished": null,
      "quiet_lively": -0.354,
      "local_chain": 0.227,
      "park": -0.782
    },
    "credit": "© lumoplank · CC0",
    "url": "https://commons.wikimedia.org/wiki/File:Bukchon,_Seoul_-_Bukchon3283.jpg"
  },
  {
    "id": "m1973956346681852",
    "src": "assets/photos/swipe/m1973956346681852.jpg",
    "place": "창경궁로",
    "scene": "Polished · chain",
    "tags": [
      "polished",
      "chain"
    ],
    "scores": {
      "touristy_local": 0.0,
      "historic_contemporary": 0.2,
      "raw_polished": 1.0,
      "quiet_lively": 0.175,
      "local_chain": 0.562,
      "park": -0.757
    },
    "credit": "CC BY-SA 4.0 (Mapillary)",
    "url": "https://www.mapillary.com/app/?pKey=1973956346681852&focus=photo"
  },
  {
    "id": "m2119683545535612",
    "src": "assets/photos/swipe/m2119683545535612.jpg",
    "place": "낙산성곽길",
    "scene": "Historic · chain",
    "tags": [
      "historic",
      "chain",
      "quiet"
    ],
    "scores": {
      "touristy_local": -0.2,
      "historic_contemporary": -1.0,
      "raw_polished": null,
      "quiet_lively": -0.73,
      "local_chain": 0.944,
      "park": 0.06
    },
    "credit": "CC BY-SA 4.0 (Mapillary)",
    "url": "https://www.mapillary.com/app/?pKey=2119683545535612&focus=photo"
  },
  {
    "id": "m229147956344960",
    "src": "assets/photos/swipe/m229147956344960.jpg",
    "place": "돈화문로10길",
    "scene": "Local · historic",
    "tags": [
      "local",
      "historic",
      "lively"
    ],
    "scores": {
      "touristy_local": 1.0,
      "historic_contemporary": -1.0,
      "raw_polished": null,
      "quiet_lively": 0.878,
      "local_chain": -0.056,
      "park": -0.824
    },
    "credit": "CC BY-SA 4.0 (Mapillary)",
    "url": "https://www.mapillary.com/app/?pKey=229147956344960&focus=photo"
  },
  {
    "id": "m26581196581506509",
    "src": "assets/photos/swipe/m26581196581506509.jpg",
    "place": "수표교 진출입 계단 9번",
    "scene": "Historic · independent",
    "tags": [
      "historic",
      "independent"
    ],
    "scores": {
      "touristy_local": 0.0,
      "historic_contemporary": -1.0,
      "raw_polished": null,
      "quiet_lively": null,
      "local_chain": -0.697,
      "park": 0.0
    },
    "credit": "CC BY-SA 4.0 (Mapillary)",
    "url": "https://www.mapillary.com/app/?pKey=26581196581506509&focus=photo"
  },
  {
    "id": "c41729552",
    "src": "assets/photos/swipe/c41729552.jpg",
    "place": "돈화문로11가길",
    "scene": "Raw · quiet",
    "tags": [
      "raw",
      "quiet",
      "chain"
    ],
    "scores": {
      "touristy_local": 0.0,
      "historic_contemporary": 0.0,
      "raw_polished": -1.0,
      "quiet_lively": -0.449,
      "local_chain": 0.339,
      "park": -0.841
    },
    "credit": "© yamarhythm · CC BY 3.0",
    "url": "https://commons.wikimedia.org/wiki/File:Back_street_(seoul,鐘路)_-_panoramio.jpg"
  },
  {
    "id": "c41729716",
    "src": "assets/photos/swipe/c41729716.jpg",
    "place": "돈화문로11가길",
    "scene": "Raw · quiet",
    "tags": [
      "raw",
      "quiet",
      "chain"
    ],
    "scores": {
      "touristy_local": 0.0,
      "historic_contemporary": 0.0,
      "raw_polished": -1.0,
      "quiet_lively": -0.449,
      "local_chain": 0.339,
      "park": -0.841
    },
    "credit": "© yamarhythm · CC BY 3.0",
    "url": "https://commons.wikimedia.org/wiki/File:Back_street_(鐘路、Seoul)_-_panoramio.jpg"
  },
  {
    "id": "c54774571",
    "src": "assets/photos/swipe/c54774571.jpg",
    "place": "인사동14길",
    "scene": "Polished · historic",
    "tags": [
      "polished",
      "historic",
      "independent",
      "lively"
    ],
    "scores": {
      "touristy_local": 0.333,
      "historic_contemporary": -1.0,
      "raw_polished": 1.0,
      "quiet_lively": 0.551,
      "local_chain": -0.697,
      "park": -1.0
    },
    "credit": "© ccfarmer · CC BY 3.0",
    "url": "https://commons.wikimedia.org/wiki/File:Back_alley_-_panoramio_(1).jpg"
  },
  {
    "id": "m642883701849178",
    "src": "assets/photos/swipe/m642883701849178.jpg",
    "place": "창경궁로",
    "scene": "Polished · chain",
    "tags": [
      "polished",
      "chain"
    ],
    "scores": {
      "touristy_local": 0.0,
      "historic_contemporary": 0.2,
      "raw_polished": 1.0,
      "quiet_lively": 0.175,
      "local_chain": 0.562,
      "park": -0.757
    },
    "credit": "CC BY-SA 4.0 (Mapillary)",
    "url": "https://www.mapillary.com/app/?pKey=642883701849178&focus=photo"
  },
  {
    "id": "m830806842673657",
    "src": "assets/photos/swipe/m830806842673657.jpg",
    "place": "계동길",
    "scene": "Local · historic",
    "tags": [
      "local",
      "historic"
    ],
    "scores": {
      "touristy_local": 0.5,
      "historic_contemporary": -0.333,
      "raw_polished": null,
      "quiet_lively": -0.247,
      "local_chain": 0.043,
      "park": -0.975
    },
    "credit": "CC BY-SA 4.0 (Mapillary)",
    "url": "https://www.mapillary.com/app/?pKey=830806842673657&focus=photo"
  },
  {
    "id": "m913715791647553",
    "src": "assets/photos/swipe/m913715791647553.jpg",
    "place": "창덕궁길",
    "scene": "Chain · quiet",
    "tags": [
      "chain",
      "quiet",
      "contemporary"
    ],
    "scores": {
      "touristy_local": -0.2,
      "historic_contemporary": 0.333,
      "raw_polished": null,
      "quiet_lively": -0.392,
      "local_chain": 0.582,
      "park": -0.335
    },
    "credit": "CC BY-SA 4.0 (Mapillary)",
    "url": "https://www.mapillary.com/app/?pKey=913715791647553&focus=photo"
  },
  {
    "id": "m919166087769798",
    "src": "assets/photos/swipe/m919166087769798.jpg",
    "place": "낙산성곽길",
    "scene": "Historic · chain",
    "tags": [
      "historic",
      "chain",
      "quiet"
    ],
    "scores": {
      "touristy_local": -0.2,
      "historic_contemporary": -1.0,
      "raw_polished": null,
      "quiet_lively": -0.73,
      "local_chain": 0.944,
      "park": 0.06
    },
    "credit": "CC BY-SA 4.0 (Mapillary)",
    "url": "https://www.mapillary.com/app/?pKey=919166087769798&focus=photo"
  }
];
