/* ============================================================
   THEME + DATA MODULE
   Single look: the WANDER design system ("Structured Fluidity").
   All UI authors against these CSS vars, so this one theme maps the
   design-system tokens (design_system/tokens/*) onto the whole app:
   - canvas    : soft teal ivory  (#C1EBE9)
   - accent    : cobalt           (#4456FF)
   - text      : seaweed ramp     (deep desaturated green, never black)
   - map data  : mint / lime / liliac / orchid semantics
   - type      : Space Grotesk (UI) + Space Mono (data layer)
   ============================================================ */

const THEMES = {
  wander: {
    name: 'Wander',
    tagline: 'Structured fluidity · soft data, crisp controls',
    dark: false,
    vars: {
      /* surfaces — tints of the teal canvas */
      '--paper': '#DFF1F1',          // light teal canvas
      '--paper-2': '#CDE9E9',        // deeper tint
      '--card': '#FFFFFF',           // white card over canvas
      '--card-2': '#EAF7F7',         // raised surface
      /* text — seaweed ramp */
      '--ink': '#143229',            // seaweed-900 (strong)
      '--ink-soft': '#255A4B',       // seaweed-500 (body)
      '--ink-faint': '#5E8A7C',      // seaweed-300 (muted)
      /* lines — hairlines at ~16/28% seaweed */
      '--line': 'rgba(37,90,75,0.16)',
      '--line-strong': 'rgba(37,90,75,0.28)',
      /* accent — cobalt, the single primary */
      '--accent': '#4456FF',         // cobalt-500
      '--accent-ink': '#FFFFFF',     // text on cobalt
      '--accent-soft': '#E3E6FF',    // cobalt-100
      /* data-viz hues — outing personalities + map semantics */
      '--a1': '#D238EB',             // orchid (alert / specialized)
      '--a2': '#C9FF46',             // lime   (preference match)
      '--a3': '#4456FF',             // cobalt (solo)
      '--a4': '#8A5BFF',             // iris   (couple)
      /* map */
      '--map-land': '#DFF1F1',       // canvas
      '--map-land-2': '#CDE9E9',     // deeper blocks
      '--map-road': 'rgba(37,90,75,0.42)',   // seaweed grid
      '--map-park': '#A6FFE8',       // mint
      '--map-water': '#9FA3FF',      // liliac
      '--zone': '#4456FF',           // cobalt radar-mist zone
      '--dot': '#4456FF', '--dot-glow': 'rgba(68,86,255,0.35)',  // wash-cobalt
      '--path': '#A6FFE8',           // mint primary safe path
      '--good': '#34C38F',           // positive (mint-green)
      '--warn': '#D238EB',           // orchid alert
      '--shadow': '0 4px 20px rgba(37,90,75,0.10)',  // soft seaweed-tinted
    },
    fontHead: "'Space Grotesk', 'Segoe UI', system-ui, sans-serif",
    fontUI: "'Space Grotesk', 'Segoe UI', system-ui, sans-serif",
    fontMono: "'Space Mono', 'SF Mono', ui-monospace, monospace",
    headWeight: 700, headTrack: '-0.02em', headStyle: 'normal',
    label: { spacing: '0.18em', transform: 'uppercase', weight: 400, font: 'mono' },
    radius: 20, radiusSm: 12, radiusPill: 999,
  },
};
const THEME_ORDER = ['wander'];

/* ---- shared content data ---- */

const HERO_PHOTO = 'assets/photos/insadong-alley.jpg';

// 1A — swipe deck. Real Jongno street photos (Wikimedia Commons + Mapillary),
// each snapped to a scored street, generated by step0_7_build_swipe_deck.py into
// app/swipe-data.js (window.SWIPE_CARDS / window.SWIPE_AXES, loaded before this
// file). The small fallback below only shows if that data file failed to load.
const SWIPE_CARDS = (window.SWIPE_CARDS && window.SWIPE_CARDS.length) ? window.SWIPE_CARDS : [
  { id: 'c1', place: '익선동 · Ikseon-dong', scene: 'Hanok lane, low foot traffic', tags: ['quiet', 'historic', 'independent'], src: HERO_PHOTO },
];

// The 6 bipolar axes the swipe teaches, [key, negPoleLabel, posPoleLabel]. Mirrors
// the manifest / rollup; +score = the SECOND (pos) pole. Fallback matches the repo.
const SWIPE_AXES = window.SWIPE_AXES || [
  ['touristy_local', 'touristy', 'local'],
  ['historic_contemporary', 'historic', 'contemporary'],
  ['raw_polished', 'raw', 'polished'],
  ['quiet_lively', 'quiet', 'lively'],
  ['local_chain', 'independent', 'chain'],
  ['park', '', 'by a park'],
];

// Which vibe SLIDER (sliders.jsx / realmap.jsx VIBE_AXES id) each score axis feeds.
// Uniform sign: slider 0 = negative pole, slider 1 = positive pole (see realmap
// VIBE_AXIS_MAP), so sliderValue = (axisScore + 1) / 2.
const AXIS_TO_SLIDER = {
  touristy_local: 'crowd', historic_contemporary: 'era', raw_polished: 'finish',
  quiet_lively: 'energy', local_chain: 'origin', park: 'green',
};
const CHIP_MIN = 0.15;     // how far an axis must lean before it becomes a profile chip

// Turn the swipe likes/dislikes into the user's base taste profile.
//   likes: { cardId: true|false }  (true = LIKE / swiped right)
// For each axis we average, over every SWIPED card that scores on that axis, the
// card's score signed by the swipe (+ for LIKE, − for NOPE): a liked historic
// street (−0.6) pulls the axis toward historic, a *disliked* one pushes it toward
// contemporary. Result per axis is a taste target in [−1, +1].
// Returns { profile, sliderVals, chips } — see commitSwipeProfile for how they land.
function computeSwipeProfile(likes, cards) {
  cards = cards || SWIPE_CARDS || [];
  likes = likes || {};
  const acc = {};                                   // axisKey -> { sum, n }
  SWIPE_AXES.forEach(([k]) => { acc[k] = { sum: 0, n: 0 }; });
  cards.forEach(c => {
    if (!(c.id in likes) || !c.scores) return;      // not swiped yet
    const sign = likes[c.id] ? 1 : -1;
    SWIPE_AXES.forEach(([k]) => {
      const v = c.scores[k];
      if (v == null) return;
      acc[k].sum += sign * v; acc[k].n += 1;
    });
  });

  const profile = {}, sliderVals = {}, chips = [];
  SWIPE_AXES.forEach(([k, neg, pos]) => {
    if (!acc[k].n) return;
    const v = clamp(acc[k].sum / acc[k].n, -1, 1);
    profile[k] = v;
    const sid = AXIS_TO_SLIDER[k];
    if (sid) sliderVals[sid] = (v + 1) / 2;         // [-1,1] axis -> [0,1] slider
    const label = v > 0 ? pos : neg;
    if (label && Math.abs(v) >= CHIP_MIN) chips.push({ key: k, label, value: v });
  });
  chips.sort((a, b) => Math.abs(b.value) - Math.abs(a.value));
  return { profile, sliderVals, chips };
}

// Persist the swipe profile so the sliders + profile screens pick it up on mount.
// Writes three keys (usePersist reads the same 'seoulwalk.'+key JSON on init):
//   swipe.profile   the raw per-axis taste target (for the profile chips)
//   sliders.vals    defaults with the swipe-derived positions merged in
//   profile.chips   ordered pole chips derived from the profile
// With no cards swiped yet it clears back to slider defaults / no chips.
function commitSwipeProfile(likes, cards) {
  const { profile, sliderVals, chips } = computeSwipeProfile(likes, cards);
  return writeProfile(profile, sliderVals, chips);
}

// How far the chosen pole leans on its axis: a moderate, refinable starting lean
// (not a hard ±1) — the map ranks by it and the user can still nudge the sliders.
const PAIR_STRENGTH = 0.6;

// Build the base profile from the forced-choice pairs (one per axis). Each answered
// pair sets its OWN axis toward the chosen pole; 'skip'/unanswered leaves it neutral.
// Because every axis is decided by an explicit either/or, nothing can cancel out the
// way a like-everything swipe does. choices: { axisKey: 'left'|'right'|'skip' }.
function computeProfileFromPairs(choices, pairs) {
  pairs = pairs || SWIPE_PAIRS || [];
  choices = choices || {};
  const profile = {}, sliderVals = {}, chips = [];
  pairs.forEach(p => {
    const ch = choices[p.axis];
    if (ch !== 'left' && ch !== 'right') return;    // unanswered or 'no preference'
    const v = ch === 'right' ? PAIR_STRENGTH : -PAIR_STRENGTH;  // right = pos pole
    profile[p.axis] = v;
    const sid = AXIS_TO_SLIDER[p.axis];
    if (sid) sliderVals[sid] = (v + 1) / 2;
    const label = v > 0 ? p.pos : p.neg;
    if (label) chips.push({ key: p.axis, label, value: v });
  });
  return { profile, sliderVals, chips };
}

function commitPairsProfile(choices, pairs) {
  const { profile, sliderVals, chips } = computeProfileFromPairs(choices, pairs);
  return writeProfile(profile, sliderVals, chips);
}

// Persist a computed profile so the sliders + profile screens pick it up on mount
// (usePersist reads the same 'seoulwalk.'+key JSON on init). Shared by both the
// pair chooser and the legacy swipe path.
function writeProfile(profile, sliderVals, chips) {
  const defVals = Object.fromEntries((VIBE_AXES || []).map(a => [a.id, a.def]));
  const write = (key, val) => { try { localStorage.setItem('seoulwalk.' + key, JSON.stringify(val)); } catch (e) {} };
  write('swipe.profile', profile);
  write('sliders.vals', { ...defVals, ...sliderVals });
  write('profile.chips', chips);
  // study telemetry: snapshot the axis-keyed preference vector as it evolves
  if (window.StudyAPI) window.StudyAPI.logProfile('onboarding', profile);
  return { profile, sliderVals, chips };
}

// Rehydrate the base profile from a cloud-returned axis vector (account recovery
// after localStorage was cleared). Rebuilds the slider positions + pole chips the
// same way writeProfile does, but does NOT re-log telemetry — this is restoring a
// past state, not producing a new one. `vector` is { axisKey: value in [-1,1] }.
// No-op (returns false) for an empty/missing vector so a blank recovery leaves the
// onboarding to run normally.
function rehydrateProfileFromVector(vector) {
  if (!vector || typeof vector !== 'object') return false;
  const profile = {}, sliderVals = {}, chips = [];
  (SWIPE_AXES || []).forEach(([k, neg, pos]) => {
    const v = vector[k];
    if (v == null || isNaN(v)) return;
    profile[k] = v;
    const sid = AXIS_TO_SLIDER[k];
    if (sid) sliderVals[sid] = (clamp(v, -1, 1) + 1) / 2;
    const label = v > 0 ? pos : neg;
    if (label && Math.abs(v) >= CHIP_MIN) chips.push({ key: k, label, value: v });
  });
  if (!Object.keys(profile).length) return false;
  chips.sort((a, b) => Math.abs(b.value) - Math.abs(a.value));
  const defVals = Object.fromEntries((VIBE_AXES || []).map(a => [a.id, a.def]));
  const write = (key, val) => { try { localStorage.setItem('seoulwalk.' + key, JSON.stringify(val)); } catch (e) {} };
  write('swipe.profile', profile);
  write('sliders.vals', { ...defVals, ...sliderVals });
  write('profile.chips', chips);
  return true;
}

// ======== GROUP TASTE MERGE ================================================
// When friends join a walk we blend everyone's taste into one vibe target.

// tiny persisted-state helpers, shared by everything below
function swRead(key, dflt) {
  try { const v = localStorage.getItem('seoulwalk.' + key); return v != null ? JSON.parse(v) : dflt; }
  catch (e) { return dflt; }
}
function swWrite(key, val) {
  try { localStorage.setItem('seoulwalk.' + key, JSON.stringify(val)); } catch (e) {}
}

// ---- declared preference LEVELS --------------------------------------------
// Two levels per axis. The tolerance band a person brings to the group negotiation
// follows from the level they DECLARED, rather than being applied blindly:
//   'off'  — "doesn't matter to me" → full-width band: never blocks, never the outlier
//   'pref' — "I have a preference"  → ±BAND_PREF, can bend to meet the group
// Indifference is stored in the SLIDERS screen's existing drop list (sliders.off,
// keyed by slider id) instead of a new key, so the two screens can never disagree
// about which dimensions count. The legacy profile.prefs chip map is still read as
// a source of 'off' so accounts that toggled chips before this existed keep them.
//
// A third level ('non-negotiable', a deliberately narrow band that refuses to bend)
// was built and then dropped: one more thing to teach a participant mid-study, for a
// mechanism the group screen can already express through a plain conflict. Restoring
// it means widening PREF_LEVELS and giving axisBand a narrower width for it — the
// rest of the chain reads whatever level it is handed.
const BAND_PREF = 0.14;
const PREF_LEVELS = ['pref', 'off'];    // the order a tap cycles through

// Slider ids the walker dropped, folding in the legacy profile.prefs toggles
// (keyed by axis, false = dropped).
function readSlidersOff() {
  const off = (swRead('sliders.off', []) || []).slice();
  const legacy = swRead('profile.prefs', {}) || {};
  Object.keys(legacy).forEach(k => {
    if (legacy[k] !== false) return;
    const sid = AXIS_TO_SLIDER[k];
    if (sid && off.indexOf(sid) < 0) off.push(sid);
  });
  return off;
}

// The level declared for one axis. `off` can be passed in to avoid re-reading
// localStorage once per axis.
function axisLevel(axis, off) {
  off = off || readSlidersOff();
  const sid = AXIS_TO_SLIDER[axis];
  return (sid && off.indexOf(sid) >= 0) ? 'off' : 'pref';
}

// Every axis with its declared level. An axis with no reading at all still gets
// one: the level says "does this count for me", not "how strongly do I lean".
function readAxisLevels() {
  const off = readSlidersOff(), out = {};
  (SWIPE_AXES || []).forEach(([k]) => { out[k] = axisLevel(k, off); });
  return out;
}

// Declare a level for one axis. Writes through to the same keys the sliders screen
// reads, retires any stale legacy chip toggle for that axis (otherwise it would
// keep forcing 'off'), and fires 'seoulwalk:prefs' so mounted screens re-read.
function setAxisLevel(axis, level) {
  const sid = AXIS_TO_SLIDER[axis];
  const off = (swRead('sliders.off', []) || []).filter(x => x !== sid);
  if (level === 'off' && sid) off.push(sid);
  swWrite('sliders.off', off);
  const legacy = swRead('profile.prefs', null);
  if (legacy && axis in legacy) { delete legacy[axis]; swWrite('profile.prefs', legacy); }
  try { window.dispatchEvent(new CustomEvent('seoulwalk:prefs', { detail: { axis, level } })); } catch (e) {}
  return level;
}

// The walker's taste as an axis vector in [-1,+1], derived from the live slider
// positions (so it tracks manual tuning), falling back to the swipe profile.
// RAW: every axis with a reading, INCLUDING ones declared "doesn't matter" — a
// screen that has to LABEL an axis still needs its lean. Anything that ranks or
// negotiates should use readUserTasteVector() instead.
function readTasteVectorRaw() {
  const vals = swRead('sliders.vals', null);
  if (!vals) return swRead('swipe.profile', {}) || {};
  const vec = {};
  Object.keys(AXIS_TO_SLIDER).forEach(ax => {
    const v = vals[AXIS_TO_SLIDER[ax]];
    if (v != null) vec[ax] = v * 2 - 1;               // [0,1] slider → [-1,+1] axis
  });
  return vec;
}

// The walker's taste as it should COUNT: the raw vector minus every axis they
// declared "doesn't matter". A dropped axis is absent rather than zero, and every
// consumer already reads a missing axis as neutral/flexible — so declaring
// indifference genuinely removes the axis from the ranking and from the group
// negotiation, instead of silently voting for the middle.
function readUserTasteVector() {
  const levels = readAxisLevels(), raw = readTasteVectorRaw(), out = {};
  Object.keys(raw).forEach(ax => { if (levels[ax] !== 'off') out[ax] = raw[ax]; });
  return out;
}

// Friends toggled to join THIS walk. Reads the persisted 'profile.friends' toggle
// map + the StudyAPI friends cache. A joining friend counts even if they have no
// taste vector yet (they're on the walk) — downstream treats a missing/empty
// profile as neutral/flexible, never a reject — so selecting one friend always
// forms a group, whether or not they've done the onboarding.
function activeJoiningFriends() {
  try {
    const joining = JSON.parse(localStorage.getItem('seoulwalk.profile.friends') || '{}');
    const all = (window.StudyAPI && window.StudyAPI.myFriends && window.StudyAPI.myFriends()) || [];
    return all.filter(f => joining[f.participant_id]);
  } catch (e) { return []; }
}

// Blend axis vectors into one, averaging per axis over ONLY the vectors that have
// an opinion on it. A missing axis counts as NEUTRAL — it's skipped, never a vote
// against — so an empty/new profile never distorts the blend. Returns {axis: val}.
function mergeTasteVectors(vectors) {
  const sums = {}, counts = {};
  (vectors || []).forEach(vec => {
    if (!vec) return;
    Object.keys(vec).forEach(ax => {
      const v = vec[ax];
      if (v == null || isNaN(v)) return;
      sums[ax] = (sums[ax] || 0) + v; counts[ax] = (counts[ax] || 0) + 1;
    });
  });
  const merged = {};
  Object.keys(sums).forEach(ax => { merged[ax] = sums[ax] / counts[ax]; });
  return merged;
}

// Explainability chips for a merged vector: the axes with the strongest shared
// lean, labelled by pole ("quiet", "local", …), for "what you all like". Returns
// ordered [{ key, label, value }].
function groupTasteChips(merged, n) {
  const chips = [];
  (SWIPE_AXES || []).forEach(([k, neg, pos]) => {
    const v = merged[k];
    if (v == null || Math.abs(v) < CHIP_MIN) return;
    const label = v > 0 ? pos : neg;
    if (label) chips.push({ key: k, label, value: v });
  });
  chips.sort((a, b) => Math.abs(b.value) - Math.abs(a.value));
  return n ? chips.slice(0, n) : chips;
}

// ======== GROUP RECONCILIATION =============================================
// The ONE place where "what does this group actually want" is computed, so the
// group screen and the map can never disagree about it. Everything here derives
// from PERSISTED state (declared levels + slider positions + the nudges the group
// applied), never from React state, because the two screens are never mounted at
// the same time — the map has to be able to read the negotiation the group screen
// left behind.

// Person hues. Cobalt is me (outing-solo in the DS); friends cycle the rest.
// Deliberately NOT the DS match/safe/alert hues, which are reserved for axis state.
const PERSON_HUES = { me: '#4456FF', friends: ['#8A5BFF', '#B84BFF', '#F59E0B', '#0EA5E9', '#EC4899', '#14B8A6'] };

// up to two uppercase initials from a display name, for the avatar disc
function tasteInitials(name) {
  const parts = String(name || '').trim().split(/\s+/).filter(Boolean);
  if (!parts.length) return '?';
  return (parts.length > 1 ? parts[0][0] + parts[1][0] : parts[0].slice(0, 2)).toUpperCase();
}

// A person's tolerance band on one axis, in slider space [0,1]. No reading, or a
// declared 'off' → the FULL width: they never block common ground and can never be
// named the outlier. Anything they declared gets the same half-width, so this is
// where a future extra level (a narrower, harder-to-bend band) would slot in.
function axisBand(value, level) {
  if (level === 'off' || value == null || isNaN(value)) return [0, 1];
  const s = (clamp(value, -1, 1) + 1) / 2;
  return [Math.max(0, s - BAND_PREF), Math.min(1, s + BAND_PREF)];
}

// intersection of N [lo,hi] intervals, or null if they don't all overlap
function axisIntersect(ints) {
  const lo = Math.max(...ints.map(r => r[0]));
  const hi = Math.min(...ints.map(r => r[1]));
  return lo < hi ? [lo, hi] : null;
}

// Classify one axis from a set of bands: everybody overlaps ('common'), one person
// apart from a majority that would agree without them ('nudge'), or nobody
// overlapping anybody ('scatter').
function mergeAxisRanges(ranges, members) {
  const all = axisIntersect(members.map(id => ranges[id]));
  if (all) return { kind: 'common', band: all };

  // who, if they bend, unlocks the widest agreement for everyone else?
  let best = null;
  members.forEach(o => {
    const band = axisIntersect(members.filter(m => m !== o).map(m => ranges[m]));
    if (band && (!best || band[1] - band[0] > best.band[1] - best.band[0])) best = { outlier: o, band };
  });
  if (best) {
    const r = ranges[best.outlier];
    return { kind: 'nudge', band: best.band, outlier: best.outlier,
      meet: (best.band[0] + best.band[1]) / 2,            // middle of where the others agree
      side: r[0] > best.band[1] ? 'right' : 'left' };     // which way the outlier leans
  }

  // Nobody overlaps anybody — meet at the MEDIAN lean and bend whoever sits
  // furthest from it. Median (not the middle element) so this holds for any group
  // size, including the couple and 4+ cases, not just three people.
  const mids = members.map(id => ({ id, mid: (ranges[id][0] + ranges[id][1]) / 2 })).sort((a, b) => a.mid - b.mid);
  const half = mids.length / 2;
  const meet = mids.length % 2 ? mids[Math.floor(half)].mid : (mids[half - 1].mid + mids[half].mid) / 2;
  const outlier = mids.reduce((f, m) => Math.abs(m.mid - meet) > Math.abs(f.mid - meet) ? m : f, mids[0]).id;
  return { kind: 'scatter', band: [meet - 0.07, meet + 0.07], outlier, meet,
    side: ranges[outlier][0] > meet ? 'right' : 'left' };
}

// ---- how a disagreement gets settled ---------------------------------------
// One conflict, four possible ways out. A settlement is stored per axis in
// 'group.settle' as { how, status, by, value?, winner?, other?, deal? }:
//
//   'middle' — go to where the group already agrees. With 3+ people that band IS the
//              majority's, so this leans toward wherever most of them are.
//   'drop'   — the axis stops shaping the walk. This is the honest answer for a PAIR
//              with no overlap: there is no majority to lean toward, and a midpoint
//              between two opposite tastes is a place neither of them asked for.
//   'point'  — a specific spot the group dragged the marker to, rather than the one
//              the app proposed.
//   'trade'  — this axis goes to one person's own zone, outright, because they gave
//              another axis away in exchange (see proposeTrade).
//
// status is 'proposed' or 'agreed', and ONLY 'agreed' moves the walk. That is the
// whole point: the app must not report an agreement that nobody consented to, so a
// proposal is visible, reversible, and inert until the person it asks something of
// accepts. `by` is who proposed it — and, while it is pending, whose turn it is to
// move the marker. Persisted rather than React state so the map sees it too, and
// written synchronously so a read right after a tap already reflects it.
const SETTLE_KEY = 'group.settle';

// My id in the negotiation. Once a walk is shared this MUST be my participant id and
// not a local alias: `by`, `asks` and `winner` travel to the other phones inside the
// document, and 'me' would resolve to "whoever is reading" on each of them. Falls back
// to 'me' only when there is no session at all (offline prototype).
function myMemberId() {
  const S = window.StudyAPI || {};
  const pid = S.myParticipantId && S.myParticipantId();
  return pid != null ? String(pid) : 'me';
}

function readSettlements() {
  const s = swRead(SETTLE_KEY, null);
  // Older single-device state wrote 'me' as the proposer. Normalise it to my real id
  // so a negotiation started before the walk existed keeps working once it is shared.
  if (s) {
    const mine = myMemberId();
    if (mine !== 'me') {
      Object.keys(s).forEach(ax => {
        if (s[ax] && s[ax].by === 'me') s[ax] = { ...s[ax], by: mine };
      });
    }
    return s;
  }
  // pre-settlement state: 'group.nudges' was a bare { axis: true } set of applied
  // middles. Read it as already-agreed so an in-progress negotiation isn't lost.
  const legacy = swRead('group.nudges', {}) || {};
  const out = {};
  Object.keys(legacy).forEach(ax => { if (legacy[ax]) out[ax] = { how: 'middle', status: 'agreed', by: myMemberId() }; });
  return out;
}

// Write locally FIRST so the tap feels instant, then push the same patch to the walk
// if there is one. The poll is what reconciles us with the other phones; on a version
// conflict the server hands back the current document and the client adopts it.
function writeSettlements(all, patch, meta) {
  swWrite(SETTLE_KEY, all);
  const S = window.StudyAPI || {};
  if (patch && S.currentWalkId && S.currentWalkId() && S.patchWalkState) S.patchWalkState(patch, meta);
  try { window.dispatchEvent(new CustomEvent('seoulwalk:groupsettle', { detail: { settlements: all } })); } catch (e) {}
  return all;
}
// Every axis a settlement covers: on its own, or the whole bargain when it is a trade.
function dealKeys(all, axis) {
  const s = all[axis];
  if (!s) return [];
  return s.deal ? Object.keys(all).filter(k => all[k] && all[k].deal === s.deal) : [axis];
}
function setSettlement(axis, s) {
  const all = readSettlements();
  // Proposing is accepting: the proposer is seeded into `accepts` so they never have to
  // confirm their own offer, and a settlement that asks nobody is agreed the moment it
  // is made.
  const rec = s ? { ...s, moving: false, accepts: s.accepts || (s.by ? [s.by] : []) } : null;
  if (rec) all[axis] = rec; else delete all[axis];
  return writeSettlements(all, { [axis]: rec }, { action: rec ? 'propose' : 'undo', axis });
}

// Live cursor. While a finger is down the position is pushed to the others, throttled,
// so they watch it move instead of only learning where it stopped. A move is not a new
// offer, it is the same one at a new place — and it RESETS `accepts`, because consent
// given to one spot is not consent to the next one. `moving` lets the other screens say
// who is dragging rather than announcing an offer on every frame.
const WALK_MOVE_MS = 250;
let _moveAt = 0, _moveTimer = null, _movePending = null;
function moveSettlement(axis, value, by) {
  _movePending = { axis, value, by };
  const send = () => {
    const m = _movePending;
    _movePending = null;
    _moveAt = Date.now();
    if (!m) return;
    const all = readSettlements();
    const rec = { ...(all[m.axis] || {}), how: 'point', value: m.value, by: m.by,
      moving: true, accepts: m.by ? [m.by] : [] };
    all[m.axis] = rec;
    writeSettlements(all, { [m.axis]: rec }, { action: 'move', axis: m.axis });
  };
  const wait = WALK_MOVE_MS - (Date.now() - _moveAt);
  if (wait <= 0) {
    if (_moveTimer) { clearTimeout(_moveTimer); _moveTimer = null; }
    send();
    return;
  }
  if (!_moveTimer) _moveTimer = setTimeout(() => { _moveTimer = null; send(); }, wait);
}

// Record ONE person's acceptance. The settlement only becomes agreed once everyone it
// asks has done this, so a three-way disagreement can't be closed by a single tap.
// A trade is one bargain over two axes, so accepting it covers both.
function acceptSettlement(axis, memberId) {
  const all = readSettlements();
  const keys = dealKeys(all, axis);
  if (!keys.length || !memberId) return all;
  const patch = {};
  keys.forEach(k => {
    const accepts = ((all[k] && all[k].accepts) || []).slice();
    if (accepts.indexOf(memberId) < 0) accepts.push(memberId);
    all[k] = { ...all[k], accepts, moving: false };
    patch[k] = all[k];
  });
  return writeSettlements(all, patch, { action: 'accept', axis });
}

// Hand the offer over: the other person becomes the proposer, keeping the value as the
// starting point for their counter. Their acceptance is implied, mine is not any more.
function counterSettlement(axis, asks) {
  const all = readSettlements();
  const keys = dealKeys(all, axis);
  if (!keys.length || !asks) return all;
  const patch = {};
  keys.forEach(k => {
    all[k] = { ...all[k], by: asks, accepts: [asks], moving: false };
    patch[k] = all[k];
  });
  return writeSettlements(all, patch, { action: 'counter', axis });
}
function clearSettlement(axis) {
  const all = readSettlements();
  const keys = dealKeys(all, axis);
  if (!keys.length) return all;
  const patch = {};
  keys.forEach(k => { delete all[k]; patch[k] = null; });
  return writeSettlements(all, patch, { action: 'undo', axis });
}
function clearGroupSettlements() {
  const patch = {};
  Object.keys(readSettlements()).forEach(k => { patch[k] = null; });
  return writeSettlements({}, Object.keys(patch).length ? patch : null, { action: 'undo' });
}

// Which way out the app offers first, given how many people are walking. A pair has
// no majority to lean toward, so it is offered the drop rather than a midpoint.
function defaultHow(memberCount) { return memberCount <= 2 ? 'drop' : 'middle'; }

// Turn a settlement into its effect on one axis. Called only for AGREED settlements;
// a pending one is previewed by the UI but must not reach here.
function applySettlement(s, ranges, base, ids) {
  if (s.how === 'drop') return { eff: ranges, band: null, center: null, idle: true };
  if (s.how === 'trade') {
    const w = ranges[s.winner] || [0, 1];
    return { eff: ranges, band: w, center: (w[0] + w[1]) / 2, idle: false };
  }
  // 'middle' and 'point' differ only in WHERE they land: the app's proposal, or the
  // spot the group dragged to. Both stretch every band to reach it, then re-classify.
  // (For 'middle' the point already sits inside the majority's band, so stretching
  // theirs is a no-op and only the outlier actually moves.)
  const meet = clamp(s.how === 'point' && s.value != null ? s.value : base.meet, 0, 1);
  const eff = {};
  ids.forEach(id => {
    const r = ranges[id];
    eff[id] = [Math.min(r[0], meet), Math.max(r[1], meet)];
  });
  const view = mergeAxisRanges(eff, ids);
  const band = view.kind === 'common' ? view.band : [meet - 0.06, meet + 0.06];
  // A dragged point is a deliberate choice, so the walk goes exactly there. A middle
  // resolves to the centre of the zone everyone now holds in common.
  return { eff, band, center: s.how === 'point' ? meet : (band[0] + band[1]) / 2, idle: false };
}

// Where a settlement puts the walk on this axis, in slider space. Null for a 'drop',
// which takes the axis off the walk entirely rather than moving it somewhere.
function settlementLanding(s, ranges, base) {
  if (!s || s.how === 'drop') return null;
  if (s.how === 'trade') {
    const w = ranges[s.winner] || [0, 1];
    return (w[0] + w[1]) / 2;
  }
  return clamp(s.how === 'point' && s.value != null ? s.value : base.meet, 0, 1);
}

// Who still has to say yes — and ONLY the people this settlement actually asks
// something of. On a spot or a middle that means whoever's own comfortable zone does
// not contain it: someone already inside the zone is being asked to concede nothing,
// so making them confirm would be theatre. Move the cursor into everyone's overlap and
// the list is empty, which settles it on the spot.
// The proposer is never on the list: offering something is accepting it.
function settlementNeeds(s, ranges, ids, landing) {
  if (!s) return [];
  if (s.how === 'trade') return s.other && s.other !== s.by ? [s.other] : [];
  // Leaving the axis out takes it away from everyone who declared anything on it.
  if (s.how === 'drop') {
    return ids.filter(id => id !== s.by && !(ranges[id][0] <= 0 && ranges[id][1] >= 1));
  }
  if (landing == null) return [];
  return ids.filter(id => {
    if (id === s.by) return false;
    const r = ranges[id] || [0, 1];
    return landing < r[0] || landing > r[1];
  });
}

// Agreed once every person it asks has accepted — so a three-way disagreement can't be
// closed by one person tapping, and one that asks nobody needs no tap at all.
// `accepts` absent means a record written before per-person acceptance existed.
function settlementAgreed(s, needed) {
  if (!s) return false;
  if (s.moving) return false;                     // still under someone's finger
  if (!s.accepts) return s.status === 'agreed';
  return (needed || []).every(id => s.accepts.indexOf(id) >= 0);
}

// Pair two open disagreements so each side wins one OUTRIGHT, instead of both living
// in a lukewarm middle on both. Returns the two halves of the bargain, or null when
// there is no pair that gives two different people something.
// This is the axis-level version of "each of us gets one" — it changes the SHAPE of
// the concession (one big loss each, instead of two small ones) rather than its size.
function proposeTrade(axes, ids) {
  const open = axes.filter(a => a.conflict && !a.applied && !a.pending && a.outlier);
  if (open.length < 2) return null;
  // Stand-in for "the majority" on an axis: of everyone except the outlier, the member
  // whose own zone sits closest to the zone the others already share.
  const majorityOf = a => {
    const mid = (a.band[0] + a.band[1]) / 2;
    const pool = ids.filter(id => id !== a.outlier);
    if (!pool.length) return null;
    const dist = id => {
      const r = a.ranges[id] || [0, 1];
      return Math.abs((r[0] + r[1]) / 2 - mid);
    };
    return pool.reduce((f, id) => (dist(id) < dist(f) ? id : f), pool[0]);
  };
  for (let i = 0; i < open.length; i++) {
    for (let j = i + 1; j < open.length; j++) {
      const A = open[i], B = open[j];
      // A goes to whoever is currently being asked to bend on it; B goes to the other
      // side. When the same person is the odd one out on both, they take A and the
      // majority takes B — so the bargain still has two different winners.
      const aWin = A.outlier;
      const bWin = B.outlier !== A.outlier ? B.outlier : majorityOf(B);
      if (!bWin || bWin === aWin) continue;
      return [{ axis: A.id, winner: aWin, other: bWin }, { axis: B.id, winner: bWin, other: aWin }];
    }
  }
  return null;
}

// Levels inferred for someone whose own declaration we don't have: an axis they have
// a reading on counts as 'pref', a missing one as 'off' — flexible, never a reject.
function levelsFromVector(vec) {
  const levels = {};
  vec = vec || {};
  (SWIPE_AXES || []).forEach(([k]) => { levels[k] = (vec[k] == null || isNaN(vec[k])) ? 'off' : 'pref'; });
  return levels;
}

// The group on THIS walk, each with the taste vector and levels the negotiation runs on.
//
// Two sources, in order of authority:
//   1. A SHARED walk — the group is its accepted members, with the taste each of them
//      froze when they accepted, mine included. Every phone therefore reconciles the
//      exact same numbers. My live sliders deliberately do NOT steer the group here:
//      once a walk is shared, the target moves by agreement, not by one person
//      dragging a slider on their own screen.
//   2. No walk — the local prototype path: me plus the friends toggled on in my
//      profile, using their latest published profile vector.
function buildGroupMembers(userVec) {
  const S = window.StudyAPI || {};
  const myName = (S.currentDisplayName && S.currentDisplayName()) || 'You';
  const myId = myMemberId();
  const walk = S.currentWalk && S.currentWalk();
  const rows = (walk && walk.members) || [];
  const accepted = rows.filter(m => m.status === 'accepted');
  const myRow = rows.find(m => String(m.participant_id) === myId);
  const iAmInvited = !!myRow && myRow.status === 'invited';

  if (accepted.length) {
    // A friend has opened a walk and I have not answered yet. Put me on the axes ANYWAY,
    // with my live taste, so the screen shows what this walk looks like with me in it —
    // otherwise being invited means watching a negotiation I am absent from. My vector is
    // not on the walk until I accept, so the other phones genuinely do not have it yet:
    // `pendingJoin` marks that, and the screen says so rather than implying I'm in.
    const list = iAmInvited ? accepted.concat([myRow]) : accepted;
    let f = 0;
    return list.map(m => {
      const id = String(m.participant_id);
      const isMe = id === myId;
      const name = isMe ? myName : (m.display_name || 'friend');
      return {
        id, name, init: tasteInitials(name), isMe,
        pendingJoin: isMe && iAmInvited,
        hue: isMe ? PERSON_HUES.me : PERSON_HUES.friends[(f++) % PERSON_HUES.friends.length],
        vec: (isMe && iAmInvited) ? (userVec || readUserTasteVector()) : (m.vector || (isMe ? (userVec || readUserTasteVector()) : {})),
        levels: (isMe && iAmInvited) ? readAxisLevels() : (m.levels || levelsFromVector(m.vector)),
      };
    });
  }

  const me = { id: myId, name: myName, init: tasteInitials(myName), isMe: true, hue: PERSON_HUES.me,
    vec: userVec || readUserTasteVector(), levels: readAxisLevels() };
  const friends = activeJoiningFriends().map((f, i) => {
    const name = f.display_name || f.friend_code || 'friend';
    const vec = f.profile || {};
    return { id: String(f.participant_id), name, init: tasteInitials(name), isMe: false,
      hue: PERSON_HUES.friends[i % PERSON_HUES.friends.length], vec, levels: levelsFromVector(vec) };
  });
  return [me].concat(friends);
}

// My own taste snapshot, as it must be frozen into a walk when I accept it.
function myWalkSnapshot() {
  return { vector: readUserTasteVector(), levels: readAxisLevels() };
}

// The full per-axis negotiation, ready for both display and ranking.
// Each axis reports BOTH what has been agreed (`applied`, which moves the walk) and
// what is merely on the table (`pending`, which doesn't) — so the screen can show an
// offer honestly without the map silently acting on it.
function reconcileGroupAxes(userVec, membersOverride) {
  const members = membersOverride || buildGroupMembers(userVec);
  const ids = members.map(m => m.id);
  const byId = Object.fromEntries(members.map(m => [m.id, m]));
  const settlements = readSettlements();
  // the clean bipolar axes only — greenery has a single pole, so it has no "middle"
  const bipolar = (SWIPE_AXES || []).filter(a => a[0] !== 'park' && a[1] && a[2]);
  const axes = bipolar.map(([key, left, right]) => {
    const ranges = {};
    members.forEach(m => { ranges[m.id] = axisBand(m.vec[key], m.levels[key]); });
    const base = mergeAxisRanges(ranges, ids);
    const conflict = base.kind !== 'common';
    const s = conflict ? settlements[key] : null;
    // Whether it is agreed is DERIVED from who has accepted, not stored: one source of
    // truth, so a settlement can never claim agreement it hasn't collected.
    const landing = settlementLanding(s, ranges, base);
    const needs = settlementNeeds(s, ranges, ids, landing);
    const agreed = settlementAgreed(s, needs);
    const applied = agreed ? s : null;
    const pending = s && !agreed ? s : null;

    const out = applied ? applySettlement(applied, ranges, base, ids)
      : { eff: ranges, band: base.band, center: base.band ? (base.band[0] + base.band[1]) / 2 : base.meet, idle: false };

    // Nobody declared anything here → the group has no opinion on this axis, and it
    // must NOT be ranked on: otherwise "we're all indifferent" would silently
    // become "we all want the exact middle".
    const noneDeclared = ids.every(id => ranges[id][0] <= 0 && ranges[id][1] >= 1);

    return {
      id: key, left, right, ranges, eff: out.eff,
      kind: base.kind, conflict, idle: noneDeclared || out.idle,
      band: out.band, center: out.center,
      outlier: base.outlier || null, side: base.side || null,
      meet: base.meet != null ? base.meet : null,
      applied, pending,
      previewAt: pending ? landing : null,   // where to draw the cursor for a live offer
      turn: s ? s.by : null,                 // whose finger the cursor is under
      moving: !!(s && s.moving),             // someone is dragging it right now
      // everyone this settlement still needs a yes from, and whether it needs any
      asks: needs,
      accepts: (s && s.accepts) || [],
    };
  });
  return { members, ids, byId, axes, settlements };
}

// THE group vibe target — the single value the group screen AND the map rank on.
// `userVecOverride` lets the map pass its live in-map slider positions instead of
// the persisted ones, so dragging a slider still re-ranks instantly.
// Returns { target, group, axes, members }; walking solo, `group` is null and the
// target is the walker's own vector untouched.
function groupTarget(userVecOverride) {
  const userVec = userVecOverride || readUserTasteVector();
  // Who counts is decided in one place (buildGroupMembers): the accepted members of a
  // shared walk if there is one, else the friends toggled on locally. Alone, nothing
  // is negotiated and the walker's own vector passes through untouched.
  const members = buildGroupMembers(userVec);
  const others = members.filter(m => !m.isMe);
  if (!others.length) return { target: userVec, group: null, axes: null, members: null };
  const rec = reconcileGroupAxes(userVec, members);
  const target = { ...userVec };
  const negotiated = {};
  rec.axes.forEach(a => {
    negotiated[a.id] = true;
    if (a.idle) { delete target[a.id]; return; }        // nobody cares → don't rank on it
    // An axis I'm indifferent about but my friends care about DOES enter the target
    // here, at the point they agreed on: "doesn't matter to me" means I never block,
    // not that the group has to drop the dimension.
    target[a.id] = clamp(a.center * 2 - 1, -1, 1);      // slider space → axis space
  });
  // Axes outside the negotiated set (greenery has one pole, so there is no middle to
  // meet at) keep the plain average over whoever has an opinion, as before.
  Object.keys(target).forEach(ax => {
    if (negotiated[ax]) return;
    const votes = [target[ax]];
    others.forEach(m => { const v = m.vec && m.vec[ax]; if (v != null && !isNaN(v)) votes.push(v); });
    target[ax] = votes.reduce((a, b) => a + b, 0) / votes.length;
  });
  return {
    target, axes: rec.axes, members: rec.members,
    group: { count: others.length, names: others.map(m => m.name) },
  };
}

// Shared street recommender — lets the Social / Group screens rank the SAME
// NLP-scored streets the map uses, by a (merged) taste vector, without owning the
// map's data pipeline. The geojson is fetched once and cached across screens.
let _vibeStreetsPromise = null;
function loadVibeStreets() {
  if (!_vibeStreetsPromise) {
    _vibeStreetsPromise = fetch('scores-named-streets-jongno.geojson')
      .then(r => r.json())
      .then(gj => (gj.features || []).filter(f => f.properties && f.properties.name))
      .catch(() => []);
  }
  return _vibeStreetsPromise;
}
// Rank streets for a taste vector (axis → weight in [-1,1]); resolves to the top
// n {name, score, sub, feature}. Reuses realmap's rankByVibe so the ordering is
// identical to the map. Returns [] until rankByVibe/data are available.
function recommendForVector(vector, n) {
  return loadVibeStreets().then(feats => {
    if (!window.rankByVibe || !feats.length) return [];
    const target = {};
    Object.keys(vector || {}).forEach(k => { if (vector[k] != null && !isNaN(vector[k])) target[k] = vector[k]; });
    if (!Object.keys(target).length) return [];
    const ranked = window.rankByVibe(target, feats);
    return n ? ranked.slice(0, n) : ranked;
  });
}
// Tiny hook: recompute recommendations whenever the taste vector changes.
function useRecommendations(vector, n) {
  const [recs, setRecs] = React.useState([]);
  const key = JSON.stringify(vector || {});
  React.useEffect(() => {
    let alive = true;
    recommendForVector(vector, n).then(r => { if (alive) setRecs(r); });
    return () => { alive = false; };
  }, [key, n]);   // eslint-disable-line react-hooks/exhaustive-deps
  return recs;
}

// ---- pair PHOTO curation (which two photos each axis comparison shows) --------
// The user can override the auto-picked exemplars from the in-app curation screen.
// Override shape: { axisKey: { left: cardId, right: cardId } }. It only changes the
// PHOTOS shown — the profile math keys off the chosen POLE, not the photo — so
// curation never affects scoring.
function cardById(id) { return (SWIPE_CARDS || []).find(c => c.id === id) || null; }

function readPairOverride() {
  try { const v = localStorage.getItem('seoulwalk.pairs.override'); return v ? JSON.parse(v) : {}; }
  catch (e) { return {}; }
}

// Merge the default auto-pairs (SWIPE_PAIRS) with the user's override into the pairs
// the onboarding actually shows: [{ axis, neg, pos, left, right }]. Drops any axis
// that can't resolve two photos.
function resolveSwipePairs(override) {
  const ov = override || readPairOverride();
  const defaults = {};
  (SWIPE_PAIRS || []).forEach(p => { defaults[p.axis] = p; });
  return (SWIPE_AXES || []).map(([axis, neg, pos]) => {
    const d = defaults[axis] || {};
    const o = ov[axis] || {};
    const left = (o.left && cardById(o.left)) || d.left || null;
    const right = (o.right && cardById(o.right)) || d.right || null;
    return { axis, neg: d.neg || neg || 'no park', pos: d.pos || pos, left, right };
  }).filter(p => p.left && p.right);
}

// 1B — vibe axes
const VIBE_AXES = [
  { id: 'era', left: 'Historic', right: 'Contemporary', def: 0.32 },
  { id: 'finish', left: 'Raw', right: 'Polished', def: 0.40 },
  { id: 'origin', left: 'Independent', right: 'Chain', def: 0.18 },
  { id: 'crowd', left: 'Touristy', right: 'Local', def: 0.62 },
  { id: 'energy', left: 'Quiet', right: 'Lively', def: 0.58 },
  { id: 'green', left: 'Greenery', right: 'Park', def: 0.66 },
];

// 2 — map. coords are % of the map viewport.
const MAP_ZONE = { cx: 52, cy: 50, r: 33 };
const MAP_SPOTS = [
  { id: 's1', name: 'Cheongsudang lane', x: 44, y: 38, match: 0.96, why: 'quiet · historic · indie' },
  { id: 's2', name: 'Seosulla tea house', x: 64, y: 30, match: 0.88, why: 'leafy · no crowds' },
  { id: 's3', name: 'Hanok bookshop', x: 38, y: 56, match: 0.82, why: 'minimal · old bookshops' },
  { id: 's4', name: 'Brick roastery', x: 60, y: 60, match: 0.74, why: 'raw · artsy' },
  { id: 's5', name: 'Lantern dessert bar', x: 52, y: 72, match: 0.66, why: 'cosy · tucked-away' },
  { id: 's6', name: 'Mural corner', x: 72, y: 50, match: 0.46, why: 'lively · young' },
  { id: 's7', name: 'Riverside underpass', x: 30, y: 40, match: 0.40, why: 'open · riverside' },
];
// dashed "local hidden path" — a route only locals know, along 서순라길
const HIDDEN_PATH = [[33, 70], [40, 60], [44, 52], [46, 42], [52, 36], [62, 31]];
// white "famous local path" — the lane everyone who lives here walks
const FAMOUS_PATH = [[26, 86], [32, 74], [38, 66], [43, 57], [48, 49], [53, 41], [59, 32], [64, 20]];
// yellow-dotted "recommended path" — what the app suggests, starting at the puck
const RECO_PATH = [[50, 68], [45, 61], [47, 53], [51, 47], [56, 43], [61, 37], [63, 28]];

// modes for screen 2
const MAP_MODES = [
  { id: 'follow', name: 'Follow', blurb: 'The app guides you, turn by turn.' },
  { id: 'modify', name: 'Modify', blurb: 'It proposes — you reshape on the fly.' },
  { id: 'background', name: 'Background', blurb: 'Stays quiet, nudges near something great.' },
];

// 3 — people + social
const PEOPLE = {
  you: { id: 'you', name: 'You', init: 'Y', hue: 'var(--accent)' },
  sora: { id: 'sora', name: 'Sora', init: 'S', hue: 'var(--a1)' },
  min: { id: 'min', name: 'Min', init: 'M', hue: 'var(--a3)' },
  jae: { id: 'jae', name: 'Jae', init: 'J', hue: 'var(--a4)' },
};
const SOCIAL = {
  solo: {
    label: 'Solo', blurb: 'Tuned only to you.',
    changes: [{ k: '+', t: 'Deep-focus spots & solo seating ranked up' }, { k: '+', t: 'Longer wander loops, fewer stops' }, { k: '–', t: 'Group-only venues hidden' }],
  },
  couple: {
    label: 'Couple', blurb: 'Blending 2 profiles.',
    changes: [{ k: '+', t: 'Date-friendly cafés ranked higher' }, { k: '+', t: 'Quieter streets you both like' }, { k: '–', t: 'Solo-only spots hidden' }],
  },
  group: {
    label: 'Group', blurb: 'Blending 3 profiles.',
    changes: [{ k: '+', t: 'Wider streets & shareable tables up' }, { k: '+', t: 'Spots near everyone\u2019s overlap zone' }, { k: '–', t: 'Tight one-seat alleys downranked' }],
  },
};

// 3B — group merge now runs on REAL taste vectors (me + joining friends), built in
// group.jsx from each person's profile. The old hardcoded GROUP_AXES / GROUP_FLAGS
// sample ranges were removed once that screen went live.

/* ---- tiny helpers ---- */
function usePersist(key, initial) {
  const [v, setV] = React.useState(() => {
    try { const s = localStorage.getItem('seoulwalk.' + key); return s != null ? JSON.parse(s) : initial; }
    catch (e) { return initial; }
  });
  React.useEffect(() => {
    try { localStorage.setItem('seoulwalk.' + key, JSON.stringify(v)); } catch (e) {}
  }, [key, v]);
  return [v, setV];
}
const prefersReduced = () => window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;

/* ---- responsive helper ----
   Live-updating boolean for a media query, so the app can switch between the
   desktop "phone mockup + side dock" layout and a full-bleed mobile web app. */
function useMediaQuery(query) {
  const [match, setMatch] = React.useState(
    () => (window.matchMedia ? window.matchMedia(query).matches : false));
  React.useEffect(() => {
    if (!window.matchMedia) return;
    const mq = window.matchMedia(query);
    const on = () => setMatch(mq.matches);
    on();
    mq.addEventListener ? mq.addEventListener('change', on) : mq.addListener(on);
    return () => { mq.removeEventListener ? mq.removeEventListener('change', on) : mq.removeListener(on); };
  }, [query]);
  return match;
}
const clamp = (n, a, b) => Math.max(a, Math.min(b, n));
const lerp = (a, b, t) => a + (b - a) * t;

/* ---- geometry → mini-map thumbnail ----
   Turn a GeoJSON geometry into a small set of [x, y] points inside a padded
   0..100 box (y flipped so geographic north points up), used to draw a favorite
   street's real shape as a card thumbnail. */
function geomSegments(geom) {
  if (!geom) return [];
  if (geom.type === 'LineString') return [geom.coordinates];
  if (geom.type === 'MultiLineString') return geom.coordinates;
  if (geom.type === 'Polygon') return geom.coordinates;
  if (geom.type === 'MultiPolygon') return geom.coordinates.flat();
  if (geom.type === 'Point') return [[geom.coordinates]];
  return [];
}
function geomToThumb(geom, maxPts = 24) {
  const segs = geomSegments(geom);
  if (!segs.length) return [];
  // pick the longest single segment for a clean, un-jumped line
  let coords = segs.reduce((a, s) => (s.length > a.length ? s : a), []);
  if (coords.length < 2) coords = segs.flat();
  if (coords.length < 2) return [];
  const xs = coords.map(c => c[0]), ys = coords.map(c => c[1]);
  const minx = Math.min(...xs), maxx = Math.max(...xs), miny = Math.min(...ys), maxy = Math.max(...ys);
  const w = (maxx - minx) || 1e-9, h = (maxy - miny) || 1e-9, sc = Math.max(w, h);
  const pad = 12, span = 100 - 2 * pad, ox = (sc - w) / 2, oy = (sc - h) / 2;
  let pts = coords.map(([x, y]) => [
    +(pad + ((x - minx) + ox) / sc * span).toFixed(1),
    +(pad + ((maxy - y) + oy) / sc * span).toFixed(1),
  ]);
  if (pts.length > maxPts) {                       // downsample so the stored favorite stays small
    const step = (pts.length - 1) / (maxPts - 1);
    pts = Array.from({ length: maxPts }, (_, i) => pts[Math.round(i * step)]);
  }
  return pts;
}

/* ---- favorites store ----
   Persisted in localStorage and shared across screens: the map writes, the
   profile reads. A custom event keeps any mounted screen live-synced. Each
   favorite = { name, sub, points, kind }. */
const FAV_KEY = 'seoulwalk.favorites';
const FAV_EVENT = 'seoulwalk:favorites';
function getFavorites() {
  try { const s = localStorage.getItem(FAV_KEY); return s ? JSON.parse(s) : []; } catch (e) { return []; }
}
function writeFavorites(list) {
  try { localStorage.setItem(FAV_KEY, JSON.stringify(list)); } catch (e) {}
  try { window.dispatchEvent(new CustomEvent(FAV_EVENT)); } catch (e) {}
}
function isFavorite(name) { return getFavorites().some(f => f.name === name); }
// Is this favorite currently shared with friends?
function isFavoriteShared(name) { return getFavorites().some(f => f.name === name && f.shared); }
// Add (newest first) or remove a favorite, keyed by name. Returns true if now saved.
// Removing a street that was shared also un-shares it, so it disappears from
// friends' maps instead of lingering after the owner drops it.
function toggleFavorite(fav) {
  const list = getFavorites();
  const i = list.findIndex(f => f.name === fav.name);
  if (i >= 0) {
    const removed = list[i];
    list.splice(i, 1);
    if (removed && removed.shared && window.StudyAPI && window.StudyAPI.unshareFavorite) {
      window.StudyAPI.unshareFavorite(removed.name);
    }
  } else {
    list.unshift(fav);
  }
  writeFavorites(list);
  return i < 0;
}
// Flip whether a saved street is shared with friends. Explicit action (separate
// from saving): the ♥ stays private until the walker chooses to push it out. Keeps
// the local `shared` flag and the cloud in sync. Returns the new shared state.
function setFavoriteShared(name, shared) {
  const list = getFavorites();
  const f = list.find(x => x.name === name);
  if (!f) return false;
  f.shared = !!shared;
  writeFavorites(list);
  const S = window.StudyAPI;
  if (S) {
    if (shared && S.shareFavorite) S.shareFavorite(f);
    else if (!shared && S.unshareFavorite) S.unshareFavorite(name);
    if (S.logEvent) S.logEvent('favorite_share', { name: name, shared: !!shared });
    // pull a fresh view so any UI listening to friends' shares stays current
    if (S.refreshFriendFavorites) setTimeout(() => S.refreshFriendFavorites(), 300);
  }
  return !!shared;
}
// Live-synced favorites list for a component.
function useFavorites() {
  const [list, setList] = React.useState(getFavorites);
  React.useEffect(() => {
    const sync = () => setList(getFavorites());
    window.addEventListener(FAV_EVENT, sync);
    window.addEventListener('storage', sync);   // sync across tabs too
    return () => { window.removeEventListener(FAV_EVENT, sync); window.removeEventListener('storage', sync); };
  }, []);
  return list;
}
// Live-synced list of streets my FRIENDS have shared (from the friend poll).
// Each item: { participant_id, display_name, street_name, edge_id, note, ts }.
function useFriendFavorites() {
  const read = () => (window.StudyAPI && window.StudyAPI.myFriendFavorites && window.StudyAPI.myFriendFavorites()) || [];
  const [list, setList] = React.useState(read);
  React.useEffect(() => {
    const sync = e => setList((e && e.detail && e.detail.favorites) || read());
    window.addEventListener('seoulwalk:friendfavorites', sync);
    return () => window.removeEventListener('seoulwalk:friendfavorites', sync);
  }, []);
  return list;
}

Object.assign(window, {
  THEMES, THEME_ORDER, HERO_PHOTO, SWIPE_CARDS, SWIPE_AXES, VIBE_AXES,
  AXIS_TO_SLIDER, computeSwipeProfile, commitSwipeProfile,
  computeProfileFromPairs, commitPairsProfile, rehydrateProfileFromVector,
  readUserTasteVector, readTasteVectorRaw, activeJoiningFriends,
  mergeTasteVectors, groupTasteChips,
  PREF_LEVELS, BAND_PREF, readAxisLevels, axisLevel, setAxisLevel,
  PERSON_HUES, tasteInitials, axisBand, axisIntersect, mergeAxisRanges,
  readSettlements, setSettlement, acceptSettlement, counterSettlement,
  moveSettlement, clearSettlement, clearGroupSettlements, defaultHow, applySettlement,
  settlementLanding, settlementNeeds, settlementAgreed,
  proposeTrade, myMemberId, levelsFromVector, myWalkSnapshot,
  buildGroupMembers, reconcileGroupAxes, groupTarget,
  loadVibeStreets, recommendForVector, useRecommendations,
  cardById, readPairOverride, resolveSwipePairs,
  MAP_ZONE, MAP_SPOTS, HIDDEN_PATH, FAMOUS_PATH, RECO_PATH, MAP_MODES, PEOPLE, SOCIAL,
  usePersist, prefersReduced, useMediaQuery, clamp, lerp,
  geomToThumb, getFavorites, isFavorite, isFavoriteShared, toggleFavorite,
  setFavoriteShared, useFavorites, useFriendFavorites,
});
